
language: node_js
node_js:
- "8"

install:
- npm install apollo-link@1.2.2 graphql@0.13.2
- npm install -g coveralls
- npm install

script:
- npm test
- npm run coverage
- coveralls < ./coverage/lcov.info || true # ignore coveralls error

# Allow Travis tests to run in containers.
# sudo: false